
// REGISTER ACTIONS
export  const REGISTER_PENDING = "REGISTER_PENDING";
export  const REGISTER_SUCCESS= "REGISTER_SUCCESS";
export  const REGISTER_COMPLETED= "REGISTER_COMPLETED";
export  const REGISTER_FAILD= "REGISTER_FAILD";

// LOGIN ACTIONS
export  const LOGIN_PENDING = "LOGIN_PENDING";
export  const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export  const LOGIN_FAILED = "LOGIN_FAILED";

export  const CLEAR_ERRORS = "CLEAR_ERRORS";

//USER 
export  const USER_LOADED = "USER_LOADED";


/// USER LOGOUT

export  const LOGOUT = "LOGOUT";